Added support for plugins.

diff --git a/bin/bashlet b/bin/bashlet
--- a/bin/bashlet
+++ b/bin/bashlet
@@ -37,8 +37,9 @@
 
 
 
-poolDir=~/.bashlets
-remoteRepo=https://raw.githubusercontent.com/bashlets/bashlets-library/master/lib
+localPool=~/.bashlets
+remoteRepoLibrary=https://raw.githubusercontent.com/bashlets/bashlets-library/master/lib
+remoteRepoPlugins=https://raw.githubusercontent.com/bashlets/bashlets-plugins/master/plugins
 
 
 function list_methods()
@@ -46,18 +47,56 @@ function list_methods()
 	declare -F | sed 's/declare -f //' | grep -v "^$FUNCNAME$"
 }
 
+function bashlet_to_name()
+{
+    local bashlet="$1"
+    
+    # plugin names are prefixed by a colon
+
+    [[ $bashlet =~ ^: ]] && {
+        basename "${bashlet:1}"
+    } || {
+        basename "${bashlet}"
+    }
+}
+
+function bashlet_to_path()
+{
+    local bashlet="$1"
+    
+    # plugin names are prefixed by a colon
+
+    [[ $bashlet =~ ^: ]] && {
+        dirname "${bashlet:1}"
+    } || {
+        dirname "$bashlet"
+    }
+}
+
 function bashlet_to_file()
 {
     local bashlet="$1"
     
-    echo "$poolDir/$bashlet"
+    # plugin names are prefixed by a colon
+
+    [[ $bashlet =~ ^: ]] && {
+        echo "$localPool/plugins/${bashlet:1}"
+    } || {
+        echo "$localPool/lib/$bashlet"
+    }
 }
 
 function bashlet_to_url()
 {
     local bashlet="$1"
     
-    echo "$remoteRepo/$bashlet"
+    # plugin names are prefixed by a colon
+
+    [[ $bashlet =~ ^: ]] && {
+        echo "$remoteRepoPlugins/${bashlet:1}"
+    } || {
+        echo "$remoteRepoLibrary/$bashlet"
+    }
 }
 
 function list_methods_in_bashlet()
@@ -79,25 +118,33 @@ function list_methods_in_bashlet()
 function download_bashlet()
 {
     local bashlet="$1"
-    local file_name="$(bashlet_to_file "$1")"
-    local url="$(bashlet_to_url "$1")"
+    local file_name="$(bashlet_to_file "$bashlet")"
+    local url="$(bashlet_to_url "$bashlet")"
 
     mkdir -p "$(dirname "$file_name")" 2> /dev/null
-    curl -s "$url" > "$file_name"
+    curl -f -s "$url" > "$file_name" || {
+        rm -f "$file_name"
+        return 1
+    }
 }
 
 function import_bashlet()
 {
     local bashlet="$1"
-    local bashlet_name="$(basename "$bashlet")"
-    local bashlet_path="$(dirname "$bashlet")"
-    local file_name="$(bashlet_to_file "$1")"
+    local bashlet_name="$(bashlet_to_name "$bashlet")"
+    local bashlet_path="$(bashlet_to_path "$bashlet")"
+    local file_name="$(bashlet_to_file "$bashlet")"
     local method_prefix="bashlets_${bashlet_path}_${bashlet_name}"
-    local method_def
+    local method_name method_def
 
-    [[ -f "$file_name" ]] || download_bashlet "$bashlet"
+    [[ -f "$file_name" ]] || download_bashlet "$bashlet" || return 1
 
     source "$file_name"
+
+    # method names of plugins are prefixed by a colon (like plugin names)
+    [[ $bashlet =~ ^: ]]                                         \
+        && method_name=":$bashlet_name"                          \
+        || method_name="$bashlet_name"
 
     method_def="function ${bashlet_name}()
     {
@@ -132,7 +179,15 @@ function import_bashlet()
 }
 
 
-import_bashlet "$1"
+[[ $# != 1 ]] && {
+    echo "Usage: bashlet <bashlet>" >&2
+    exit 1
+}
+
+import_bashlet "$1" || {
+    echo "Error!" >&2
+    exit 1
+}
 
 
 # Local variables:
