bin/bashlets is now the only library entry point.

diff --git a/bin/bashlets b/bin/bashlets
--- a/bin/bashlets
+++ b/bin/bashlets
@@ -40,6 +40,11 @@
 ################################################################################
 
 BASHLETS_BASE=~
+BASHLETS_NAME=bashlets
+BASHLETS_BASE=~/.bashlets
+BASHLETS_LOADER_2ND_STAGE="$BASHLETS_BASE/core/${BASHLETS_REV:-DEFAULT}/bin/bashlets-import"
+BASHLETS_ERRORS_LOADING_ERROR=1
+
 
 
 #
@@ -72,23 +77,31 @@ trap cleanup EXIT
 
 
 #
-# parse command line options
+# core logic
 ################################################################################
 
-[[ $# -gt 0 ]] || {
-    echo ; usage
-    exit 1
-}
+# check if we are being sourced
+if [[ "${BASH_SOURCE[0]}" != "$0" ]]
+then
+    # load second stage
+    [[ -r "$BASHLETS_LOADER_2ND_STAGE" ]] || {
+        echo "[$BASHLETS_NAME] Second-stage loader not found!" >&2
+        return $BASHLETS_ERRORS_LOADING_ERROR
+    }
+    source "$BASHLETS_LOADER_2ND_STAGE" "$@"
+else
+    # parse command line options
+    [[ $# -gt 0 ]] || {
+        echo ; usage
+        exit 1
+    }
 
-verb=$1
-shift 1
+    verb=$1
+    shift 1
 
-
-#
-# execute verb
-################################################################################
-
-bashlets-$verb "$@"
+    # execute verb
+    bashlets-$verb "$@"
+fi
 
 
 # Local variables:
